### ISSUE TITLE
Redmine >= 5 compatibility

### ISSUE THREAD

**Issue by imThief** [haru/redmine_theme_changer#19]
Hi there.

Looks like plugin is incompatible with Redmine version 5 and above, trying to install - getting this
```
# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
ArgumentError: couldn't find login name -- expanding `~'
/var/lib/gems/2.7.0/gems/yard-0.9.28/lib/yard/config.rb:95:in `expand_path'
/var/lib/gems/2.7.0/gems/yard-0.9.28/lib/yard/config.rb:95:in `<class:Config>'
/var/lib/gems/2.7.0/gems/yard-0.9.28/lib/yard/config.rb:86:in `<module:YARD>'
/var/lib/gems/2.7.0/gems/yard-0.9.28/lib/yard/config.rb:2:in `<top (required)>'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/2.7.0/gems/yard-0.9.28/lib/yard.rb:13:in `<module:YARD>'
/var/lib/gems/2.7.0/gems/yard-0.9.28/lib/yard.rb:2:in `<top (required)>'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
/opt/redmine/lib/tasks/yardoc.rake:2:in `<top (required)>'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `load'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `block in load'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `load'
/var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:675:in `block in run_tasks_blocks'
/var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:675:in `each'
/var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:675:in `run_tasks_blocks'
/var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/application.rb:528:in `run_tasks_blocks'
/var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:464:in `load_tasks'
/var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/railtie.rb:207:in `public_send'
/var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/railtie.rb:207:in `method_missing'
/opt/redmine/Rakefile:7:in `<top (required)>'
/var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by haru** [comment]
I think it's not this plugins's problem.

**Comment by imThief** [comment]
Okay, thanks for the reply anyway, I have poor knowledge in ruby, unfortunately... but still will try to fix it.
Will describe resolution if succeed.
